# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: GitHub Pages deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Installing my packages
        run: yarn install --frozen-lockfile
        working-directory: ./frontend

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_NEXT_PUBLIC_STRAPI_API_URL: ${{ secrets.NEXT_STRAPI_API_URL }}
          directory: ./frontend
          file_name: .env
          fail_on_empty: false

      - name: Build my App
        run: yarn run export && touch ./out/.nojekyll
        working-directory: ./frontend

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          folder: ./frontend/out # The folder the action should deploy.
